apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
  labels:
    app: flaskapp
spec:
  type: NodePort
  selector:
    app: flaskapp
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      nodePort: 31391